### PR TITLE
Add requirements.txt and update README

### PR DESCRIPTION
**Pull request by Valken**
Added requirements.txt file with required Pillow, QT5 and Requests dependencies and updated README with instruction on how to run application

### CODE REVIEW

**Comment by razor85** [comment]
Thanks for the PR, I'd change some things:

1. Setting the version to a specific number will break installations in the future. We don't care about minor version changes since they don't break the API.
2. I'm not a fan of creating a virtual environment on user home folder. I'd advise either the user installs this globally (in case he don't know what he is doing) or he handles this by his own (in case he knows what he is doing).

Thanks anyway, if you change those I can merge them in :)

**Comment by Valken** [comment]
Thanks for the feedback! I've updated ``requirements.txt`` so that versions aren't specified, and removed virtual environment references from the readme.

**Comment by razor85** [comment]
You're welcome! Just one little small thing I noticed now: the 'python' command is the alias used by most OSes for the 'python3' executable, so I'd say the proper way to call this is 'python' (in Windows for example there is no python3 by default).

**Comment by Valken** [comment]
Ah yeah, made the changes on MacOS which is still python 2.whatever by default! Updated now.

**Pull request merged**
